import {getChatGPTUser} from '../../chatgpt-auth';
import {database,bucket,administrator} from '@/db/raw';
export const dynamic='force-dynamic';
const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
const now=()=>new Date().toISOString();
const clean=(v:unknown,max=3000)=>typeof v==='string'?v.trim().slice(0,max):'';
export async function GET(req:Request){try{const url=new URL(req.url);const action=url.searchParams.get('action');const db=database();
 if(action==='directory'){const r=await db.prepare('SELECT id,kind,name,category,city,region,phone,description,latitude,longitude,status,code,verified_at,updated_at FROM records WHERE published=1 ORDER BY name').all();return json({records:r.results})}
 if(action==='verify'){const code=clean(url.searchParams.get('code'),80);if(!code)return json({error:'Saisissez une référence.'},400);const r=await db.prepare('SELECT id,kind,name,status,code,verified_at FROM records WHERE code=? AND published=1').bind(code.toUpperCase()).first();return json({record:r})}
 const user=await getChatGPTUser();if(!user)return json({error:'Connectez-vous pour accéder à votre espace.'},401);
 if(action==='account'){const [profile,docs,products]=await Promise.all([db.prepare('SELECT * FROM profiles WHERE owner=?').bind(user.userId).first(),db.prepare('SELECT id,name,size,created_at FROM documents WHERE owner=? ORDER BY created_at DESC').bind(user.userId).all(),db.prepare("SELECT id,name,status FROM records WHERE owner=? AND kind='produit' ORDER BY updated_at DESC").bind(user.userId).all()]);return json({profile,documents:docs.results,products:products.results})}
 if(action==='document'){const id=clean(url.searchParams.get('id'),100);const doc=await db.prepare('SELECT * FROM documents WHERE id=?').bind(id).first<any>();if(!doc||doc.owner!==user.userId&&!administrator(user.email))return json({error:'Document non accessible.'},404);const obj=await bucket().get(doc.object_key);if(!obj)return json({error:'Document introuvable.'},404);return new Response(obj.body,{headers:{'Content-Type':doc.mime,'Content-Disposition':"attachment; filename*=UTF-8''"+encodeURIComponent(doc.name),'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}})}
 if(action==='admin'){if(!administrator(user.email))return json({error:'Ce compte n’est pas habilité. L’accès doit être attribué à une adresse administratrice avant l’examen des dossiers.'},403);const [records,messages,logs,docs]=await Promise.all([db.prepare('SELECT * FROM records ORDER BY updated_at DESC').all(),db.prepare('SELECT * FROM messages ORDER BY created_at DESC LIMIT 200').all(),db.prepare('SELECT * FROM audit ORDER BY created_at DESC LIMIT 200').all(),db.prepare('SELECT id,owner,name FROM documents').all()]);return json({records:records.results,messages:messages.results,logs:logs.results,documents:docs.results})}
 return json({error:'Ressource introuvable.'},404)
 }catch(e){console.error('WARAKA read failed',e);return json({error:'Le chargement est momentanément indisponible. Réessayez.'},503)}}
export async function POST(req:Request){try{const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)return json({error:'Origine non autorisée.'},403);const user=await getChatGPTUser();if(!user)return json({error:'Connectez-vous pour enregistrer votre contribution.'},401);const action=new URL(req.url).searchParams.get('action');const db=database();
 if(action==='upload'){if(Number(req.headers.get('content-length')||0)>5.5*1024*1024)return json({error:'Le fichier dépasse 5 Mo.'},413);const f=(await req.formData()).get('file');if(!(f instanceof File)||!['application/pdf','image/jpeg','image/png'].includes(f.type)||f.size>5*1024*1024||f.size===0)return json({error:'Choisissez un PDF, JPEG ou PNG de moins de 5 Mo.'},400);const count=await db.prepare('SELECT COUNT(*) as n FROM documents WHERE owner=?').bind(user.userId).first<any>();if(count.n>=20)return json({error:'La limite de 20 documents est atteinte. Contactez l’équipe.'},400);const bytes=await f.arrayBuffer();const magic=new Uint8Array(bytes.slice(0,8));const valid=f.type==='application/pdf'?String.fromCharCode(...magic.slice(0,5))==='%PDF-':f.type==='image/png'?magic[0]===137&&magic[1]===80&&magic[2]===78&&magic[3]===71:magic[0]===255&&magic[1]===216&&magic[2]===255;if(!valid)return json({error:'Le contenu du fichier ne correspond pas au format annoncé.'},400);const id=crypto.randomUUID();const key='documents/'+user.userId+'/'+id;await bucket().put(key,bytes,{httpMetadata:{contentType:f.type}});try{await db.prepare('INSERT INTO documents (id,owner,name,size,mime,object_key,created_at) VALUES (?,?,?,?,?,?,?)').bind(id,user.userId,clean(f.name,200),f.size,f.type,key,now()).run()}catch(e){await bucket().delete(key);throw e}return json({ok:true,id})}
 if(Number(req.headers.get('content-length')||0)>24000)return json({error:'Le contenu est trop volumineux.'},413);let b:any;try{b=await req.json()}catch{return json({error:'Les informations transmises sont invalides.'},400)}
 if(action==='profile'){const name=clean(b.name,120),category=clean(b.category,120),city=clean(b.city,120),region=clean(b.region,80),description=clean(b.description,3000),role=clean(b.role,30);if(!name||!category||!city||!region||!description||!b.consent||!['praticien','entreprise','utilisateur'].includes(role))return json({error:'Complétez les champs obligatoires et acceptez les conditions.'},400);const lat=b.latitude===''||b.latitude==null?null:Number(b.latitude),lon=b.longitude===''||b.longitude==null?null:Number(b.longitude);if(lat!==null&&(!Number.isFinite(lat)||Math.abs(lat)>90)||lon!==null&&(!Number.isFinite(lon)||Math.abs(lon)>180))return json({error:'Coordonnées géographiques invalides.'},400);const stamp=now();await db.batch([db.prepare("INSERT INTO profiles (owner,name,role,category,city,region,phone,languages,hours,address,latitude,longitude,description,consent,status,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,1,'Brouillon',?) ON CONFLICT(owner) DO UPDATE SET name=excluded.name,role=excluded.role,category=excluded.category,city=excluded.city,region=excluded.region,phone=excluded.phone,languages=excluded.languages,hours=excluded.hours,address=excluded.address,latitude=excluded.latitude,longitude=excluded.longitude,description=excluded.description,consent=1,status='Brouillon',updated_at=excluded.updated_at").bind(user.userId,name,role,category,city,region,clean(b.phone,30),clean(b.languages,150),clean(b.hours,200),clean(b.address,250),lat,lon,description,stamp),db.prepare("UPDATE records SET published=0,status='Brouillon',updated_at=? WHERE owner=? AND kind!='produit'").bind(stamp,user.userId)]);return json({ok:true})}
 if(action==='submit'){const p=await db.prepare('SELECT * FROM profiles WHERE owner=?').bind(user.userId).first<any>();const d=await db.prepare('SELECT id FROM documents WHERE owner=? LIMIT 1').bind(user.userId).first();if(!p||!d||p.role==='utilisateur')return json({error:'Un profil professionnel complet et au moins un document sont nécessaires.'},400);const stamp=now();await db.batch([db.prepare("INSERT INTO records (id,owner,kind,name,category,city,region,phone,description,latitude,longitude,status,published,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,'En cours de vérification',0,?) ON CONFLICT(id) DO UPDATE SET kind=excluded.kind,name=excluded.name,category=excluded.category,city=excluded.city,region=excluded.region,phone=excluded.phone,description=excluded.description,latitude=excluded.latitude,longitude=excluded.longitude,status='En cours de vérification',published=0,updated_at=excluded.updated_at").bind('profile-'+user.userId,user.userId,p.role,p.name,p.category,p.city,p.region,p.phone,p.description+'\n\nLangues : '+p.languages+'\nHoraires : '+p.hours+'\nAdresse : '+p.address,p.latitude,p.longitude,stamp),db.prepare("UPDATE profiles SET status='En cours de vérification',updated_at=? WHERE owner=?").bind(stamp,user.userId)]);return json({ok:true})}
 if(action==='product'){const name=clean(b.name,120),manufacturer=clean(b.manufacturer,180),category=clean(b.category,100),composition=clean(b.composition,1800),description=clean(b.description,1800);if(!name||!manufacturer||!category||!composition||!description)return json({error:'Complétez les informations obligatoires du produit.'},400);const p=await db.prepare('SELECT city,region FROM profiles WHERE owner=?').bind(user.userId).first<any>();if(!p)return json({error:'Enregistrez d’abord votre profil professionnel.'},400);const id=crypto.randomUUID();await db.prepare("INSERT INTO records (id,owner,kind,name,category,city,region,description,status,published,updated_at) VALUES (?,?,'produit',?,?,?,?,?,'En cours de vérification',0,?)").bind(id,user.userId,name,category,p.city,p.region,description+'\n\nFabricant déclaré : '+manufacturer+'\nComposition déclarée : '+composition+'\nAutorisation déclarée : '+(clean(b.authorization,100)||'Non renseignée'),now()).run();return json({ok:true,id})}
 if(action==='message'){const message=clean(b.message,3000);if(!message||!['contact','partenariat','signalement'].includes(b.kind))return json({error:'Renseignez votre message.'},400);const count=await db.prepare('SELECT COUNT(*) as n FROM messages WHERE owner=? AND created_at>?').bind(user.userId,new Date(Date.now()-3600000).toISOString()).first<any>();if(count.n>=15)return json({error:'Trop de messages. Veuillez réessayer plus tard.'},429);await db.prepare('INSERT INTO messages (id,owner,kind,name,email,target,message,created_at) VALUES (?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),user.userId,b.kind,clean(b.name,120),clean(b.email,200)||user.email,clean(b.target,200),message,now()).run();return json({ok:true})}
 if(action==='review'){if(!administrator(user.email))return json({error:'Accès administrateur requis.'},403);const id=clean(b.id,120),note=clean(b.note,1500);if(!note||!['approve','reject'].includes(b.decision))return json({error:'Précisez une décision et le périmètre du contrôle.'},400);const record=await db.prepare('SELECT * FROM records WHERE id=?').bind(id).first<any>();if(!record)return json({error:'Dossier introuvable.'},404);const approve=b.decision==='approve';if(approve){const doc=await db.prepare('SELECT id FROM documents WHERE owner=? LIMIT 1').bind(record.owner).first();if(!doc)return json({error:'Au moins un document est requis avant validation.'},400)}const status=approve?'Documents vérifiés':'À corriger';const stamp=now();const code=record.code||('WRK-'+crypto.randomUUID().slice(0,8).toUpperCase());const statements=[db.prepare('UPDATE records SET status=?,published=?,code=?,verified_at=?,updated_at=? WHERE id=?').bind(status,approve?1:0,code,approve?stamp:null,stamp,id),db.prepare('INSERT INTO audit (id,actor,action,target,note,created_at) VALUES (?,?,?,?,?,?)').bind(crypto.randomUUID(),user.userId,status,id,note,stamp)];if(record.kind!=='produit')statements.push(db.prepare('UPDATE profiles SET status=?,review_note=?,updated_at=? WHERE owner=?').bind(status,note,stamp,record.owner));await db.batch(statements);return json({ok:true})}
 return json({error:'Action inconnue.'},404)
 }catch(e){console.error('WARAKA write failed',e);return json({error:'L’enregistrement a échoué. Vos champs sont conservés ; vous pouvez réessayer.'},503)}}
