export const plants = [
 {id:'prunus-africana',name:'Prunus africana',latin:'Prunus africana (Hook.f.) Kalkman',common:'Prunier d’Afrique',category:'Arbre',region:'Hautes terres',image:'/images/plant-0.jpg',description:'Un arbre des forêts tropicales de montagne, au cœur d’un patrimoine botanique à documenter et à préserver.',source:'https://powo.science.kew.org/taxon/urn%3Alsid%3Aipni.org%3Anames%3A729417-1/general-information'},
 {id:'ndole',name:'Ndolé',latin:'Vernonia amygdalina',common:'Bitter leaf',category:'Arbuste',region:'À documenter',image:'/images/plant-1.jpg',description:'Une entrée de l’herbier WARAKA consacrée au ndolé. Les noms locaux, les usages et les observations de terrain restent à documenter.',source:''},
 {id:'moringa',name:'Moringa',latin:'Moringa oleifera',common:'Moringa',category:'Arbre',region:'À documenter',image:'/images/plant-2.jpg',description:'Une fiche de découverte pour rassembler progressivement les références botaniques, les observations et les connaissances associées au moringa.',source:''}
];
export const articles = [
 {id:'documenter-les-savoirs',title:'Préserver les savoirs commence par les documenter.',category:'Tradition',image:'/images/news-0.jpg',intro:'Qui transmet un savoir ? D’où vient-il ? À quelle plante se rapporte-t-il ? La démarche documentaire de WARAKA commence par ces questions.',sections:[['Donner du contexte aux connaissances','Un nom local, une région, une langue, un récit : chaque information mérite de conserver son contexte. WARAKA propose de relier les témoignages, les fiches botaniques et leurs références, sans effacer leur origine.'],['Respecter celles et ceux qui transmettent','La collecte doit reposer sur un consentement explicite. Une connaissance n’est pas nécessairement destinée à être diffusée publiquement. Sa contribution et ses conditions de publication doivent être discutées avec son détenteur.'],['Rendre les limites visibles','Une fiche peut être incomplète. WARAKA préfère signaler un champ à documenter plutôt que de présenter une information incertaine comme un fait établi.']]},
 {id:'comprendre-les-statuts',title:'Que signifie une vérification WARAKA ?',category:'Décryptage',image:'/images/news-1.jpg',intro:'Une identité, un document, une information scientifique : ces trois éléments ne se vérifient pas de la même manière.',sections:[['Un statut, un périmètre précis','Une identité vérifiée signifie que des éléments d’identité ont été examinés. Elle ne prouve ni l’efficacité d’un traitement, ni une autorisation d’exercice.'],['Des documents traçables','Le statut documentaire doit préciser la nature des pièces consultées et la date du contrôle. Les pièces privées restent accessibles uniquement à leur propriétaire et aux personnes habilitées.'],['Une référence à consulter','WARAKA Verify permet de retrouver le statut enregistré d’une référence. Une référence introuvable ne suffit pas à conclure à une fraude.']]},
 {id:'lire-une-fiche',title:'Tradition, recherche, réglementation : trois regards distincts.',category:'Recherche',image:'/images/news-2.jpg',intro:'Lire une fiche documentaire, c’est aussi comprendre ce qu’elle permet — et ce qu’elle ne permet pas — de conclure.',sections:[['Le savoir traditionnel','Cette rubrique décrit un usage rapporté, son origine et sa source. Elle ne constitue pas une prescription.'],['La recherche scientifique','La rubrique scientifique doit présenter les références et leurs limites. Dans cette première édition, les données cliniques n’ont pas été évaluées par WARAKA.'],['Le statut réglementaire','Un produit ou un praticien doit faire l’objet d’un examen documentaire distinct. Un référencement dans un annuaire ne vaut pas autorisation officielle.']]}
];
export const regions=['Adamaoua','Centre','Est','Extrême-Nord','Littoral','Nord','Nord-Ouest','Ouest','Sud','Sud-Ouest'];
